import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
import {spawn,type ChildProcess} from 'node:child_process';
import fixture from '../fixtures/synthetic.scene.json';
import {createHash} from 'node:crypto';
import {selectSyntheticSet} from './synthetic-selection';
const message='This build isn’t ready yet. We’ve added it to our building list. Come back later to see what’s new!';
const evidence='var/evidence/public-portal';
let server:ChildProcess;
test.beforeAll(async()=>{
  await mkdir(evidence,{recursive:true});
  server=spawn('.venv/bin/python',['-m','uvicorn','guide2build.public:app','--host','127.0.0.1','--port','8002'],{env:{...process.env,PYTHONPATH:'apps/api/src',GUIDE2BUILD_PUBLIC_STORE:'sqlite',GUIDE2BUILD_PUBLIC_DB:`${evidence}/requests-${Date.now()}.sqlite3`},stdio:'ignore'});
  await expect.poll(async()=>{try{return (await fetch('http://127.0.0.1:8002/api/v1/health')).status;}catch{return 0;}}).toBe(200);
});
test.afterAll(()=>server?.kill());
test('real public portal records unavailable and unknown requests without private routes',async({page})=>{
  const privateRequests:string[]=[];
  page.on('request',r=>{if(/\/api\/v1\/(conversions|jobs|sources|reconstructions)\b|assets-local/.test(r.url()))privateRequests.push(r.url());});
  await page.goto('http://127.0.0.1:8002/');
  await page.getByLabel('Your set number').selectOption('30669');await page.getByRole('button',{name:'Find my set',exact:true}).click();
  await expect(page.getByRole('status').filter({hasText:message})).toBeVisible();
  await expect(page.getByRole('button',{name:/Prepare|conversion|Open tutorial/})).toHaveCount(0);
  await expect(page.getByRole('link',{name:'View official instructions'})).toBeVisible();
  await page.screenshot({path:`${evidence}/desktop-not-ready.png`});
  await page.getByRole('button',{name:'Close booklet selection'}).click();
  await page.setViewportSize({width:390,height:844});
  const unknown=await page.request.get('http://127.0.0.1:8002/api/v1/sets/99998');
  expect(await unknown.json()).toMatchObject({set_number:'99998',name:null,official_page:null,guides:[]});
  expect((await page.request.post('http://127.0.0.1:8002/api/v1/requests',{data:{set_number:'99998'}})).ok()).toBe(true);
  await page.getByLabel('Your set number').selectOption('60400');await page.getByRole('button',{name:'Find my set',exact:true}).click();
  await expect(page.getByRole('status').filter({hasText:message})).toBeVisible();
  await expect(page.getByRole('link',{name:'View official instructions'})).toBeVisible();
  await expect(page.getByText('Official source found.',{exact:false})).toHaveCount(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:`${evidence}/phone-not-ready.png`});
  expect(privateRequests).toEqual([]);
  for(const path of ['conversions','jobs/example','sources/example/pages/0','reconstructions/example/scene'])expect((await page.request.get(`http://127.0.0.1:8002/api/v1/${path}`)).status()).toBe(404);
});
test('failed request never claims it was added and supports retry',async({page})=>{
  await page.route('**/api/v1/requests',r=>r.fulfill({status:429,json:{detail:{code:'request_capacity',message:'Our building list is busy. Please try again tomorrow.'}}}));
  await page.goto('http://127.0.0.1:8002/');await page.getByRole('button',{name:'Find my set',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('building list is busy');await expect(page.getByText(message,{exact:true})).toHaveCount(0);
  await page.unroute('**/api/v1/requests');await page.getByRole('button',{name:'Request this set',exact:true}).click();
  await expect(page.getByText(message,{exact:true})).toBeVisible();
});
test('synthetic release transport preserves section resets, attachment identity and official links only',async({page})=>{
  // Transport fixture, not a published tutorial or reconstruction accuracy claim.
  const steps=fixture.steps.map((s,index)=>({...s,section_id:index<2?'first':'second',main_step_number:index<2?s.main_step_number:1}));
  const chunks=steps.map((s,index)=>{const body=JSON.stringify({steps:[s]});return {body,index,path:`chunks/${index}.json`,sha256:createHash('sha256').update(body).digest('hex'),bytes:Buffer.byteLength(body),step_ids:[s.step_id]};});
  const manifest={...fixture,schema_version:'2.0',release_sha256:'a'.repeat(64),sources:[{guide_id:'synthetic',source_sha256:fixture.source_sha256,official_url:'https://www.lego.com/test.pdf',page_count:4}],sections:['first','second'].map(section_id=>({section_id,source_sha256:fixture.source_sha256,label:section_id})),step_index:steps.map(({poses,visible_instance_ids,active_instance_ids,...step},chunk_index)=>({...step,chunk_index,visible_instance_count:visible_instance_ids.length,active_instance_count:active_instance_ids.length})),chunks:chunks.map(({body,...c})=>c),asset_base_url:'/published-assets/synthetic/',geometry_base_url:'/published-assets/synthetic/ldraw/'};
  const requested:string[]=[];page.on('request',r=>requested.push(r.url()));
  await page.route('**/api/v1/sets/99999',r=>r.fulfill({json:{set_number:'99999',name:'Synthetic transport fixture',official_page:'https://www.lego.com/',guides:[{guide_id:'synthetic',label:'Synthetic transport fixture',pdf_url:'https://www.lego.com/test.pdf',expected_main_steps:null,tutorial_available:true}]}}));
  await page.route('**/api/v1/sets/99999/guides/synthetic/release',r=>r.fulfill({json:manifest}));
  let releaseThird!:()=>void;const thirdChunk=new Promise<void>(resolve=>{releaseThird=resolve;});
  await page.route('**/published-assets/synthetic/chunks/*.json',async r=>{const index=Number(r.request().url().split('/').at(-1)!.split('.')[0]);if(index===2)await thirdChunk;const chunk=chunks[index];return r.fulfill({body:chunk.body,contentType:'application/json'});});
  await page.route('**/published-assets/synthetic/ldraw/**',r=>r.fulfill({status:404}));
  await page.goto('http://127.0.0.1:8002/');await selectSyntheticSet(page);await page.getByRole('button',{name:'Find my set',exact:true}).click();await page.getByRole('button',{name:'Open tutorial',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Step 1',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Review candidate'})).toHaveCount(0);
  await expect(page.getByRole('link',{name:'Open official booklet'})).toHaveAttribute('href','https://www.lego.com/test.pdf#page=1');
  await page.getByRole('button',{name:'Go to main step 1 in second',exact:true}).click();
  await expect(page.getByText('Loading this instruction…',{exact:true})).toBeVisible();
  await expect(page.locator('.viewport')).toHaveCount(0);releaseThird();
  await expect(page.getByText('No new pieces.',{exact:false})).toBeVisible();
  await expect(page.locator('.viewport')).toHaveAttribute('data-step-id','s3');
  await page.getByRole('button',{name:'Full parts list',exact:true}).click();await expect(page.locator('.parts-table')).toContainText('×2');
  await expect(page.getByRole('alert').filter({hasText:'Required geometry unavailable'})).toBeVisible();
  expect(requested.some(url=>/\/api\/v1\/(sources|reconstructions)|assets-local/.test(url))).toBe(false);
  expect(requested.some(url=>url.startsWith('https://www.lego.com/'))).toBe(false);
});
